---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "pretextgraph"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::pretextgraph=0.0.6"
